approximation: exact
backend: layer
batch_size: 50
dataset: mnist
exp_name: hessian_approx/[backend_layer]_[approximation_exact]_[no_conv_True]_[use_var_decoder_False]_
hessian_scale: 1
latent_size: 2
missing_data_imputation: false
no_conv: true
ood: true
ood_dataset: kmnist
posthoc: true
pretrained: false
test_samples: 100
train: true
use_var_decoder: false
