alpha: 0
approximation: approx
backend: layer
batch_size: 50
dataset: mnist
exp_name: hessian_approx/[backend_layer]_[approximation_approx]_[no_conv_True]_[train_samples_1]_
hessian_memory_factor: 0.999
hessian_scale: 1
latent_size: 2
missing_data_imputation: false
no_conv: true
one_hessian_per_sampling: false
ood: true
ood_dataset: kmnist
posthoc: false
pretrained: false
prior_precision: 1
test_samples: 100
train: true
train_samples: 1
update_hessian: true
