approximation: exact
backend: layer
batch_size: 50
dataset: mnist
exp_name: kl_experiment/[backend_layer]_[approximation_exact]_[no_conv_True]_[train_samples_1]_
hessian_memory_factor: 0
kl_weight: 0
latent_size: 2
no_conv: true
one_hessian_per_sampling: false
ood: false
ood_dataset: mnist
pretrained: false
test_samples: 100
train: true
train_samples: 1
