# experiment name
exp_name : "mnist_model_selection/"

# training
train : True

# test
ood : False

# data
dataset : "mnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2
use_var_decoder : False