# experiment name
exp_name : "mnist_model_selection/"

# training
train : False
kl_weight: 1e-6
train_samples: 1

# test
ood : False
missing_data_imputation : False
test_samples: 100

# data
dataset : "mnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2

# hessian
backend : "layer" 
approximation : "exact" #block, exact, approx, mix
hessian_memory_factor : 0
one_hessian_per_sampling : False