# experiment name
exp_name : "mnist_model_selection/"

# training
train : True
kl_weight: 0.0001

# test
ood : False
missing_data_imputation : False

# data
dataset : "mnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2
use_var_decoder : True