# experiment name
exp_name : "ood_experiment/"

# training
train : True

# test
ood : True

# data
dataset : "cifar10"
ood_dataset : "svhn"
batch_size: 200

# model
pretrained : False
no_conv : False
latent_size : 512
use_var_decoder : False