# experiment name
exp_name : "ood_experiment/"

# training
train : True
learning_rate : 1e-4

# test
ood : True

# data
dataset : "cifar10"
ood_dataset : "svhn"
batch_size: 50

# model
pretrained : False
no_conv : False
latent_size : 512
use_var_decoder : True