# experiment name
exp_name : "ood_experiment/"

# training
train : True
learning_rate : 1e-4

# test
ood : True
test_samples: 100

# data
dataset : "cifar10"
ood_dataset : "svhn"
batch_size: 50

# model
pretrained : False
use_var_decoder : False
no_conv : False
latent_size : 512
dropout_rate: 0.2