
# experiment name
exp_name : "ood_experiment/"

# training
train : False
posthoc : True

# test
ood : True
test_samples: 100
missing_data_imputation : False

# data
dataset : "cifar10"
ood_dataset : "svhn"
batch_size: 1

# model
pretrained : False
no_conv : False
latent_size : 512
use_la_encoder : True # this will fit the laplace to both encoder and decoder
use_var_decoder : False

# hessian
backend : "layer" 
approximation : "mix" #block, exact, diag, mix