# experiment name
exp_name : "ood_experiment/"

# training
train : True
posthoc : False
alpha: 1e-6
train_samples: 1
learning_rate : 1e-4
prior_precision: 1

# test
ood : True
missing_data_imputation : False
test_samples: 100

# data
dataset : "cifar10"
ood_dataset : "svhn"
batch_size: 8

# model
pretrained : False
no_conv : False
latent_size : 512

# hessian
backend : "layer" 
approximation : "mix" #block, exact, diag, mix
hessian_memory_factor : 0.99
one_hessian_per_sampling : True
update_hessian : True
hessian_scale : 1