# experiment name
exp_name : "ood_experiment/"

# training
train : False
kl_weight: 1e-6
learning_rate : 1e-4

# test
ood : True
missing_data_imputation : False

# data
dataset : "cifar10"
ood_dataset : "svhn"
batch_size: 50

# model
pretrained : False
no_conv : False
latent_size : 512
use_var_decoder : True