batch_size: 50
dataset: fashionmnist
dropout_rate: 0.2
exp_name: ood_experiment/[no_conv_False]_[dropout_rate_0.2]_[use_var_decoder_False]_
latent_size: 2
no_conv: false
ood: true
ood_dataset: mnist
pretrained: false
test_samples: 100
train: true
use_var_decoder: false
