batch_size: 50
dataset: cifar10
dropout_rate: 0.2
exp_name: ood_experiment/[no_conv_True]_[dropout_rate_0.2]_[use_var_decoder_False]_
latent_size: 256
learning_rate: 1e-4
no_conv: true
ood: true
ood_dataset: svhn
pretrained: false
test_samples: 100
train: true
use_var_decoder: false
