approximation: mix
backend: layer
batch_size: 50
dataset: fashionmnist
exp_name: ood_experiment/[backend_layer]_[approximation_mix]_[no_conv_False]_[train_samples_1]_
hessian_memory_factor: 0
kl_weight: 1e-6
latent_size: 2
missing_data_imputation: false
no_conv: false
one_hessian_per_sampling: false
ood: true
ood_dataset: mnist
posthoc: false
pretrained: false
test_samples: 100
train: true
train_samples: 1
