alpha: 0
approximation: approx
backend: layer
batch_size: 50
dataset: fashionmnist
exp_name: ood_experiment/large_model[backend_layer]_[approximation_approx]_[no_conv_False]_[train_samples_1]_
hessian_memory_factor: 0.999
hessian_scale: 1
latent_size: 2
missing_data_imputation: false
no_conv: false
one_hessian_per_sampling: false
ood: true
ood_dataset: mnist
posthoc: false
pretrained: false
prior_precision: 1
test_samples: 100
train: true
train_samples: 1
update_hessian: true
