batch_size: 50
dataset: cifar10
exp_name: ood_experiment/[no_conv_False]_[use_var_decoder_True]_
kl_weight: 1e-6
latent_size: 512
learning_rate: 1e-4
missing_data_imputation: false
no_conv: false
ood: true
ood_dataset: svhn
pretrained: false
train: true
use_var_decoder: true
