batch_size: 50
dataset: mnist
exp_name: hessian_approx/[no_conv_False]_[use_var_decoder_False]_
latent_size: 2
learning_rate: 1e-3
no_conv: false
ood: true
ood_dataset: kmnist
pretrained: false
train: true
use_var_decoder: false
