batch_size: 50
dataset: cifar10
exp_name: ood_experiment/[no_conv_True]_[use_var_decoder_False]_
latent_size: 256
learning_rate: 1e-4
no_conv: true
ood: true
ood_dataset: svhn
pretrained: false
train: true
use_var_decoder: false
