# experiment name
exp_name : "ood_experiment/"

# training
train : True

# test
ood : True

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : False
latent_size : 2
use_var_decoder : True