# experiment name
exp_name : "ood_experiment/"

# training
train : True

# test
test_samples: 100
ood : True

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size : 50
    
# model
pretrained : False
no_conv : True
latent_size : 2
use_la_encoder : False # this will fit the laplace to both encoder and decoder