
# experiment name
exp_name : "ood_experiment/"

# training
train : True

# test
ood : True
test_samples: 100

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2
use_la_encoder : True # this will fit the laplace to both encoder and decoder
use_var_decoder : False