# experiment name
exp_name : "ood_experiment/"

# training
train : True
kl_weight: 0.0001

# test
ood : True
missing_data_imputation : False

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2
use_var_decoder : True