approximation: mix
backend: layer
batch_size: 50
dataset: fashionmnist
exp_name: ood_experiment/[backend_layer]_[approximation_mix]_[no_conv_False]_[use_var_decoder_False]_
latent_size: 2
no_conv: false
ood: true
ood_dataset: mnist
posthoc: true
pretrained: false
test_samples: 100
train: true
use_la_encoder: true
use_var_decoder: false
