
# experiment name
exp_name : "cifar10_mix_med/"

# training
train : True
kl_weight: 1e-6
train_samples: 10

# test
ood : False
missing_data_imputation : False
test_samples: 100

# data
dataset : "cifar10"
ood_dataset : "kmnist"
batch_size: 50
    
# model
pretrained : False
no_conv : False
latent_size : 128

# hessian
backend : "layer" 
approximation : "mix" #block, exact, diag, mix
hessian_memory_factor : 0.8
one_hessian_per_sampling : False