batch_size: 50
dataset: fashionmnist
exp_name: ood_experiment/[no_conv_False]_[use_var_decoder_True]_
kl_weight: 1.0e-05
latent_size: 2
learning_rate: 1e-4
missing_data_imputation: false
no_conv: false
ood: true
ood_dataset: mnist
pretrained: false
train: true
use_var_decoder: true
