# experiment name
exp_name : ""

# training
train : True

# test
ood : False

# data
dataset : "protein"
ood_dataset : "kmnist"
batch_size: 128
    
# model
use_var_decoder : False
no_conv : True
latent_size : 2
loss_fn: "categorical"