# experiment name
exp_name : ""

# training
train : True
kl_weight: 1e-6
train_samples: 10

# test
ood : False
missing_data_imputation : False
test_samples: 100

# data
dataset : "protein"
ood_dataset : "kmnist"
batch_size: 24
    
# model
pretrained : False
no_conv : True
latent_size : 2
loss_fn : "categorical"

# hessian
backend : "layer" 
approximation : "approx"
hessian_memory_factor : 0.9
one_hessian_per_sampling : False
