
# experiment name
exp_name : ""

# training
train : True
kl_weight: 1e-6
train_samples: 1

# test
ood : False
missing_data_imputation : False
test_samples: 100

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 24
    
# model
pretrained : False
no_conv : True
latent_size : 2
loss_fn : "mse"

# hessian
backend : "layer" 
approximation : "exact" #block, exact, approx, mix
hessian_memory_factor : 0
one_hessian_per_sampling : False
