# training
train : True
kl_weight: 0.01

# test
ood: False

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 128
    
# model
use_var_decoder : False
no_conv: True
latent_size: 2
loss_fn: "mse"