alpha: 0
approximation: mix
backend: layer
batch_size: 50
dataset: celeba
exp_name: 15_05[backend_layer]_[approximation_mix]_[no_conv_False]_[train_samples_1]_
hessian_memory_factor: 0.999
hessian_scale: 1
latent_size: 128
learning_rate: 1e-4
missing_data_imputation: false
no_conv: false
one_hessian_per_sampling: false
ood: true
ood_dataset: celeba
posthoc: false
pretrained: false
prior_precision: 1
test_samples: 100
train: true
train_samples: 1
update_hessian: true
