# experiment name
exp_name : "hessian_approx/"

# training
train : True
posthoc : False
alpha : 0.0001
train_samples: 1
prior_precision: 1

# test
ood : True
test_samples: 100
missing_data_imputation: False

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2

# hessian
backend : "layer" 
approximation : "exact" #block, exact, diag, mix
hessian_memory_factor : 0.99
one_hessian_per_sampling : False
update_hessian : True
hessian_scale : 1