# experiment name
exp_name : "hessian_approx/"

# training
train : True
posthoc : True

# test
ood : True
test_samples: 100
missing_data_imputation: False

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2
use_var_decoder : False

# hessian
backend : "layer" 
approximation : "approx" #block, exact, diag, mix
hessian_scale : 1