approximation: exact
backend: layer
batch_size: 50
dataset: mnist
exp_name: kl_experiment/kl_1e-7/[backend_layer]_[approximation_exact]_[no_conv_True]_[train_samples_1]_
hessian_memory_factor: 0
kl_weight: 1e-8
latent_size: 2
missing_data_imputation: false
no_conv: true
one_hessian_per_sampling: false
ood: true
ood_dataset: kmnist
pretrained: false
test_samples: 100
train: true
train_samples: 1
